--- #YAML:1.0
name:               Net-Fluidinfo
version:            0.45
abstract:           A Perl interface to Fluidinfo
author:
    - Xavier Noria <fxn@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:          0
    JSON::XS:             0
    LWP:                  0
    Moose:                0
    MooseX::ClassAttribute:  0
    Test::Simple:         0.87
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
